// AmirHossein Roodaki

import javax.swing.JOptionPane;
import java.util.Random;

public class Number_Guessing_Game {
	public static void main(String[] args) {
		JOptionPane.showMessageDialog(null,
				"Welcome to the NumberGuessing 2-Player Game!\n\nGoal:\nGuessing the Number that Was Randomly Generated By the System in Range of 1 & 100."
						+ "\n\nRules:\nPlayers Each Turn Guess a Number Interchangeably.\nIf the Guessed Number is Equal to System's Number, That Player Win."
						+ "\nOtherwise the Number's Range Will Get Smaller & The Other Player Can Guess .\n\n* Players Can Guess as Many as They Want.\n\nGood Luck!",
				"Welcome Note", JOptionPane.INFORMATION_MESSAGE);

		String player1 = JOptionPane.showInputDialog(null, "Please Enter First Player's Name:", "Name Input",
				JOptionPane.QUESTION_MESSAGE);
		String player2 = JOptionPane.showInputDialog(null, "Please Enter Second Player's Name:", "Name Input",
				JOptionPane.QUESTION_MESSAGE);

		// Generating a Random Number Between 1 & 100
		Random random = new Random();
		int number = random.nextInt(100) + 1;

		int user_guess;
		int lower_bond = 1, upper_bond = 100;
		int counter = 0;
		boolean continue_playing = true;

		while (continue_playing) {
			if (counter % 2 == 0)
				user_guess = Integer
						.parseInt(
								JOptionPane.showInputDialog(null,
										"It's " + player1 + "'s Turn.\n" + "Please Guess a Number Between " + lower_bond
												+ " & " + upper_bond + ":",
										"Number Input", JOptionPane.QUESTION_MESSAGE));
			else
				user_guess = Integer
						.parseInt(
								JOptionPane.showInputDialog(null,
										"It's " + player2 + "'s Turn.\n" + "Please Guess a Number Between " + lower_bond
												+ " & " + upper_bond + ":",
										"Number Input", JOptionPane.QUESTION_MESSAGE));
			// System.out.print("\nPlease Guess a Number Between " + lower_bond + " & " +
			// upper_bond + ": ");

			// A Condition to Check if the Entered Number is Between the Bonds
			if ((lower_bond > user_guess || user_guess > upper_bond)) {
				JOptionPane.showMessageDialog(null, "Entered Number is out of Range.\nPlease Enter a Valid Number.",
						"Invalid Input Number!", JOptionPane.ERROR_MESSAGE);
				continue;
			}

			if (user_guess == number) {
				if (counter % 2 == 0)
					JOptionPane.showMessageDialog(null,
							"Correct Guess!\n" + player1 + " Wins!" + "\nThe Number Was " + number + ".",
							"Congratulations!", JOptionPane.INFORMATION_MESSAGE);
				else
					JOptionPane.showMessageDialog(null,
							"Correct Guess!\n" + player2 + " Wins!" + "\nThe Number Was " + number + ".",
							"Congratulations!", JOptionPane.INFORMATION_MESSAGE);

				continue_playing = JOptionPane.showConfirmDialog(null, "Do You Want to Continue Playing?",
						"Continue Option", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0 ? true : false;

				if (continue_playing) {
					number = random.nextInt(100) + 1;
					lower_bond = 1;
					upper_bond = 100;
					counter = 0;
				} else
					break;

			} else if (user_guess < number) {
				JOptionPane.showMessageDialog(null, "Wrong Guess!\nGuessed Number Was Smaller Than the Answer!",
						"Wrong Guess!", JOptionPane.WARNING_MESSAGE);
				lower_bond = user_guess;
				counter++;
			} else {
				JOptionPane.showMessageDialog(null, "Wrong Guess!\nGuessed Number Was Greater Than the Answer!",
						"Wrong Guess!", JOptionPane.WARNING_MESSAGE);
				upper_bond = user_guess;
				counter++;
			}
		}

		JOptionPane.showMessageDialog(null,
				"Thanks for Playing.\nHope You've Enjoyed.\n\nThis Game Was Written & Developed by AmirHossein Roodaki - 9935707",
				"GoodBye Note", JOptionPane.INFORMATION_MESSAGE);
	}
}